server:
  port: 80

spring:
  datasource:
    druid:
      url: jdbc:mysql://59.110.90.98:3306/book
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 617620
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
#      开启MP日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
